### ISSUE TITLE
Technical Test Planning

### ISSUE THREAD

**Issue by LangLoffelLako** [ALLUOS/ALLUOS.github.io#22]
**Description**

Design test cases, that ensure the implementation of the requirements and ensure the functionality of the application through bug detection. Prepare the execution and the documentation of the tests designed.

**Out of scope**

- Develop test scripts
- Bug fixing
- Extensive unit testing

** Tasks **

- [x] Design test cases
- [x] Decide on tests and develop documentation strategies
- [ ] Report bugs and requirement failures

**Comment by LangLoffelLako** [comment]
This is a specification of https://github.com/ALLUOS/ALLUOS.github.io/issues/19#issue-634822079
